main:
  params: [input]
  steps:

    - publishLoan:
        try:
          call: googleapis.pubsub.v1.projects.topics.publish
          args:
            topic: projects/SEU_PROJETO_ID/topics/orders
            body:
              messages:
                - data: ${base64.encode(text.encode(json.encode_to_string(input)))}
          result: publishResult

        retry:
          predicate: ${http.default_retry_predicate}
          max_retries: 3
          backoff:
            initial_delay: 2
            max_delay: 10
            multiplier: 2

    - finish:
        return:
          status: SUCCESS
          messageId: ${publishResult.messageIds[0]}