name: Deploy Cloud Function and Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: project-ab4fa986-e441-43f4-9fe
      SERVICE_ACCOUNT_DO_CI_CD: projects/1036053475221/locations/global/workloadIdentityPools/github/providers/github
      PROVIDER_DO_WORKLOAD_IDENTITY: github-actions-deploy@project-ab4fa986-e441-43f4-9fe.iam.gserviceaccount.com

    steps:

      - name: Checkout
        uses: actions/checkout@v7

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env. PROVIDER_DO_WORKLOAD_IDENTITY }}
          service_account: ${{ env. SERVICE_ACCOUNT_DO_CI_CD }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy LoanHandlerPubSub \
            --gen2 \
            --runtime=go124 \
            --region=us-central1 \
            --project="$PROJECT_ID" \
            --entry-point=LoanHandler \
            --trigger-topic=orders

      - name: Deploy Workflow
        run: |
          gcloud workflows deploy loan-workflow \
            --location=us-central1 \
            --project="$PROJECT_ID" \
            --source=workflow.yaml